### ISSUE TITLE
Reference script and material...?

### ISSUE THREAD

**Issue by dalu** [FearlessHyena/unity-basic-grpc#1]
I'm not a Medium member so I can't comment there.

I created the script and now you're just running straight away.

>     We’ll add the call to the server in GetColor() later
>     Once we’ve added the code we should see a field in the Inspector to add the Material. Let’s add the CubeMat to that field

Where how we added the code? I have edited the .cs file with VS Code.

What now?

**Comment by FearlessHyena** [comment]
Hi @dalu sorry for the delay in replying

When you got to that point in the Medium article did you also create the `ColorRandomizer.cs` file and add this code block to it?

```csharp
using UnityEngine;

public class ColorRandomizer : MonoBehaviour {

    public Material material;
    
    private readonly Color _defaultColor = Color.red;


    public void ChangeColor() {
        material.color = GetColor(material.color);
    }

    //We'll use this method to get a color from the server later
    private Color GetColor(Color currentColor) {
        Debug.Log("Got a request to change the color");
        return _defaultColor;
    }
}
```
You need to then attach that script to an Empty GameObject 
Once you do that you should see a field in the inspector to add the Material

**Comment by dalu** [comment]
You're not writing that anywhere in the post.
You're writing:

> The script will need a reference to the Material that we created earlier and a public method for changing the color that we’ll link with the Randomize Button’s OnClick handler

> Add the code below to the ColorRandomizer.cs you just created above

> In the code above you’ll notice that all we’re doing in GetColor() outputting a message to Debug.Log() and setting the colour to Red. Don’t worry we’ll add the call to the server later

> Now save ColorRandomizer.cs and you should see a field in the Inspector to add the Material. Let’s add the CubeMat to that field

And then you're already testing. No mention about any GameObject or whatever, but all of a sudden there's a Randomizer in the left panel

So now I did:

- create empty GameObject
- rename to Randomizer
- attach ColorRandomizer script
- attach CubeMat to script
- in the onClick of the Button I click + and reference the ColorRandomizer script, also set "Runtime Only" "No function" and below is the ColorRandomizer reference

**Comment by dalu** [comment]
Ok the linking the onClick handler with something was explained in this video:

https://www.youtube.com/watch?v=TYzdhiRiKd0

But you know what would be really interesting?

Doing the same with the EntitySystem. Since ECS has data (struct types) and data processors that should get interesting with grpc.

Anyhow, thanks for the tutorial and response.
